development:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_db_development
  pool: 5
  host: localhost
<<<<<<< HEAD
  username: asad
  password: 'password'
=======
  username: postgres
  password: '123456'
>>>>>>> master

test:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_db_test
  pool: 5
  host: localhost
<<<<<<< HEAD
  username: asad
  password: 'password'
=======
  username: postgres
  password: '123456'
>>>>>>> master

staging:
  url: <%= ENV['DATABASE_URL'] %>
production:
  url: <%= ENV['DATABASE_URL'] %> 
