development:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_db_development
  pool: 5
  host: localhost
  username: asad
  password: 'password'

test:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_db_test
  pool: 5
  username: asad
  password: 'password'

staging:
  url: <%= ENV['DATABASE_URL'] %>
production:
  url: <%= ENV['DATABASE_URL'] %> 
